#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x6_3(KC_DEL, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC, KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_DOT, MT(MOD_LSFT,KC_Z), KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, MT(MOD_RSFT,KC_SLSH), KC_BSLS, KC_LCTL, KC_LALT, LGUI_T(KC_SPC), LT(1,KC_TAB), LT(2,KC_ENT), LT(3,KC_GRV)),
    [1] = LAYOUT_split_3x6_3(KC_NO, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_ESC, KC_AMPR, KC_ASTR, KC_MINS, KC_EQL, KC_NO, KC_NO, KC_LBRC, KC_LPRN, KC_RPRN, KC_RBRC, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_CIRC, KC_NO, KC_NO, KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_RSFT, KC_NO, KC_LCTL, KC_LALT, LGUI_T(KC_SPC), KC_NO, KC_NO, KC_NO),
    [2] = LAYOUT_split_3x6_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_NO, KC_NO, KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_RSFT, KC_NO, KC_LCTL, KC_LALT, LGUI_T(KC_SPC), KC_NO, KC_NO, KC_NO),
    [3] = LAYOUT_split_3x6_3(KC_VOLU, RM_TOGG, RM_NEXT, RM_HUEU, RM_SATU, KC_NO, KC_NO, KC_NO, KC_NO, KC_F11, KC_F12, KC_PGUP, KC_VOLD, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_PGDN, KC_MUTE, KC_LSFT, KC_NO, KC_NO, KC_NO, QK_BOOT, QK_RBT, KC_NO, KC_NO, KC_NO, KC_RSFT, KC_NO, KC_LCTL, KC_LALT, LGUI_T(KC_SPC), KC_NO, TG(4), KC_NO),
    [4] = LAYOUT_split_3x6_3(KC_ESC, KC_Q, KC_W, KC_E, KC_1, KC_2,KC_NO, KC_NO, KC_NO, KC_NO, KC_VOLU, KC_NO, KC_LSFT, KC_A, KC_S, KC_D, KC_3, KC_4, KC_NO, KC_NO, KC_NO, KC_NO, KC_VOLD, KC_NO, KC_LCTL, KC_Z, KC_X, KC_C, KC_5, KC_6, KC_NO, KC_NO, KC_NO, KC_NO, KC_MUTE, TG(4), MO(5), KC_SPC, KC_T, KC_NO, KC_NO, KC_NO),
    [5] = LAYOUT_split_3x6_3(KC_NO, KC_NO, KC_NO, KC_R, KC_7, KC_8,KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TAB, KC_NO, KC_NO, KC_F, KC_9, KC_0, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_CAPS, KC_NO, KC_NO, KC_NO, KC_V, KC_B, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};

void keyboard_post_init_user(void) {
    rgb_matrix_enable_noeeprom();
    rgb_matrix_mode_noeeprom(RGB_MATRIX_SOLID_COLOR);
    rgb_matrix_sethsv_noeeprom(HSV_PURPLE); // pick your color
}


#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C

